services:
  - type: web
    name: chaincert-backend-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: chaincert
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false

